version: "3"
services:
  master:
    container_name: master
    image: arjones/pyspark:2.4.5
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      SPARK_NO_DAEMONIZE: 1
    ports:
      - "4040:4040"   # Spark UI
      - "6066:6066"   # REST API
      - "7077:7077"   # Spark master
      - "8080:8080"   # Web UI
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker1:
    container_name: worker1
    image: arjones/pyspark:2.4.5
    command: ["/opt/spark/sbin/start-slave.sh", "spark://master:7077"]
    environment:
      SPARK_NO_DAEMONIZE: 1
      SPARK_WORKER_WEBUI_PORT: 8081
    depends_on:
      - master
    ports:
      - "8081:8081"
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker2:
    container_name: worker2
    image: arjones/pyspark:2.4.5
    command: ["/opt/spark/sbin/start-slave.sh", "spark://master:7077"]
    environment:
      SPARK_NO_DAEMONIZE: 1
      SPARK_WORKER_WEBUI_PORT: 8082
    depends_on:
      - master
    ports:
      - "8082:8082"
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  jupyter:
    container_name: jupyter
    image: arjones/pyspark:2.4.5
    environment:
      SPARK_MASTER: spark://master:7077
    depends_on:
      - master
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
      - ./dataset:/dataset
      - ./code:/app
